# Development Dockerfile (Monorepo Friendly)
FROM golang:1.25-alpine

RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

# Root project directory
WORKDIR /app/services/payment

EXPOSE 50052

CMD ["air", "-c", ".air.toml"]